#!/bin/bash
echo -e "\Removing files generated by ATD..."
atd_files=`ls *.atd`

for atd_file in $atd_files
do
  name=`echo "$atd_file" | cut -d'.' -f 1`
  echo -e "\n=> File $atd_file :"
  
  echo "> removing ${name}_t.ml* files..."
  rm ${name}_t.ml ${name}_t.mli

  echo "> removing ${name}_j.ml* files..."
  rm ${name}_j.ml ${name}_j.mli
  
  echo "> removing ${name}_v.ml* files..."
  rm ${name}_v.ml ${name}_v.mli

done

echo -e "\nAll files generated by ATD successfully removed!\n"